apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-istio-app
  labels:
    app: golang-istio-app
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: golang-istio-app
  template:
    metadata:
      labels:
        app: golang-istio-app
      annotations:
        prometheus.io/scrape: "{{ .Values.prometheus.scrape }}"
        prometheus.io/port: "{{ .Values.prometheus.port }}"
        prometheus.io/path: "{{ .Values.prometheus.path }}"
    spec:
      containers:
        - name: golang-istio-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
